# Generated by Django 5.2.4 on 2026-09-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='stripe_payment_intent',
        ),
    ]
